### ISSUE TITLE
AutoMapper.Collection.EFCore

### ISSUE THREAD

**Issue by albertolo** [AutoMapper/AutoMapper.Collection.EFCore#28]
Hi, 

I'm trying to use AutoMapper.Collection.EFCore, in a asp. net core 3 web api. 

Does this library works with .net core 3?  

If it I added the documentation code to my method ConfigureServices in my Startup 

    services
        .AddEntityFrameworkInMemoryDatabase()
        .AddDbContext<InventarioDbContext>();

             services.AddAutoMapper((serviceProvider, automapper) =>
             {
                automapper.AddProfile(typeof(InventarioMappingProfile));
                automapper.AddCollectionMappers();
                automapper.UseEntityFrameworkCoreModel<InventarioDbContext>(serviceProvider);
             }, typeof(InventarioDbContext).Assembly);

     var serviceProvider = services.BuildServiceProvider();

Is this the right way of doing it?

**Comment by Tasteful** [comment]
The test is using efcore2 but I expect that it should work.

In your example you are configure two different dbcontext, will it work better if you use the same dbcontext for both the efcore configuration and automapper? What the exception you are getting?

**Comment by albertolo** [comment]
> The test is using efcore2 but I expect that it should work.
> 
> In your example you are configure two different dbcontext, will it work better if you use the same dbcontext for both the efcore configuration and automapper? What exception you are getting?

Sorry, it's the same I already update the issue.   I tried the following code, and It finally work my mappings, I will now try to use the Colletion Mappers. 

         services.AddAutoMapper(typeof(InventarioMappingProfile)); //original
         services.AddAutoMapper((serviceProvider, automapper) =>
         {
            automapper.AddCollectionMappers();
            automapper.UseEntityFrameworkCoreModel<InventarioDbContext>(serviceProvider);
         }, typeof(InventarioDbContext).Assembly);

**Comment by Victor-Nyagudi** [comment]
**Question on using mapping profiles** 

Since using `AutoMapper.Collection` and `AutoMapper.Collection.EntityFramework` in ASP.NET Core requires you to set up the mapping configuration in a different way, do we need to get rid of the initial mapping profile we created and use `automapper.CreateMap<>` inside the `IMapperConfigurationExpression` for all mapping, or everything should work as far as mapping collections (including child  properties of an entity that are collections) after adding this in `Program.cs`:


```
services.AddAutoMapper((serviceProvider, automapper) =>
{        
  automapper.AddCollectionMappers();
  automapper.UseEntityFrameworkCoreModel<DbContext>(serviceProvider);
}, typeofDbContext).Assembly);
```

**Comment by jbogard** [comment]
That works fine, every map inside there is created under a default profile.

**Comment by Victor-Nyagudi** [comment]
> That works fine, every map inside there is created under a default profile.

How does it know to map what to what? 

I tried commenting out one of the `CreateMap<>` methods in my mapping profile and got an error. 

Nothing's really changed for me after that piece of code, so I'm wondering, am I missing something? 

The collection in question (which is a child property of an entity) is still being cleared first resulting in `ChangeTracker` throwing an exception as it's trying to track a new instance instead of using the one in the DB.
