### ISSUE TITLE
[Issue] Stackoverflow on InsertOrUpdate recursive Entity

### ISSUE THREAD

**Issue by redradist** [AutoMapper/AutoMapper.Collection.EFCore#43]
Hi,

Recently I have found this exciting package, but when I have stared my tests on recursive Entity I have found a stackoverflow error ...

Seems like if I have many to many relation then cannot update is recursivly

**Comment by Tasteful** [comment]
I think you recursively errors belongs to the AutoMapper and not this package. This package will find an exising entity to map to instead of cleaning destination collection and map all items into new objects that AutoMapper is doing.

Can you provide some tests that we can execute for investigation? And also the beginning on the callstack to easy see howe methods call each other.

**Comment by redradist** [comment]
> 
> 
> I think you recursively errors belongs to the AutoMapper and not this package. This package will find an exising entity to map to instead of cleaning destination collection and map all items into new objects that AutoMapper is doing.
> 
> Can you provide some tests that we can execute for investigation? And also the beginning on the callstack to easy see howe methods call each other.

@Tasteful Thanks for quick feedback,

No, it is not related to AutoMapper because if I use raw AutoMapper this error do not happens ... It happens only with InsertOrUpdate call

Okay, I will try to provide simple example for this issue

**Comment by redradist** [comment]
@Tasteful Here is the example https://github.com/redradist/AutoMapper.Collection.EFCore-ReproducedExample

In this example throws the exception, but if you will try to add UseEntityFrameworkCoreModel you will get the stackoverflow

**Comment by redradist** [comment]
@Tasteful I have also added two separate branches with stackoverflow ( stackoverflow_error ) and without stackoverflow ( no_ stackoverflow_error )

**Comment by redradist** [comment]
@Tasteful Seems like I have figured out that when I add `cfg.AddCollectionMappers();` then mapping broken and it does not work anymore

**Comment by TylerCarlson1** [comment]
Few things I see with your example
1. Your `ViewModel` doesn't have the `StoreItemEntity` equivalent.  If you had that class in ViewModel your mappings wouldn't have to do any special 'AfterMap' with the remove and add functionality
2. If that doesn't cause the problem, the fact that you have a circular reference in your ViewModels from Store to times in a problem.  You need it going only one way either Stores to items, or Items to stores in your view models.  Having that circular dependency causes AutoMapper issues in general.
3. Even if this works without the circular reference issue you'll most likely be plagued with the other issues found that will cause problems.  For instance if Element 2 works and you want to link an existing item to a store that won't be possible and you'll have to do a separate kind of save because it will always generate a new item even if it already exists in the database.  If you try to fix this by only attaching the linking table then you will need to InsertOrUpdate new items first, then link it by matching ID's to the store.  At this point either solution is going to be a big hack to make it work for every scenario involved.
