### ISSUE TITLE
dynamic use of UseEntityFrameworkCoreModel

### ISSUE THREAD

**Issue by dansharpe83** [AutoMapper/AutoMapper.Collection.EFCore#46]
in our project we have multiple contexts, we would like to be able to register them all by using something similar to this:
```
services.AddAutoMapper((s,a) => {
                a.AddCollectionMappers();
                //add all the contexts in
                var types = assemblies.SelectMany(a => a.DefinedTypes.Where(d => d.IsAssignableFrom(typeof(DbContext)))).ToList();
                foreach(var type in types)
                {
                    a.UseEntityFrameworkCoreModel(type, s);
                }
            })
```

as opposed to having to know all the types to pass into into the current `UseEntityFrameworkCoreModel<TContext>` method.

could there be more extensions to this method that takes a Type parameter and not have the <TContext> like the AddScoped service etc?

just wanted to check this isnt a stupid idea before seeing if i can mod the code myself?

**Comment by TylerCarlson1** [comment]
It needs the type because it creates a new instance of the item to do its configuration.
It could be set to pass the instance you want itself instead of having to generate a new one and that would be how it would work because Generic Arguement only allows parameterless constructor which you can't enforce at compile time.  Then you could instantiate your DbContexts and then pass them over through the UseEntityFrameworkCoreModel
