### ISSUE TITLE
DB first issue

### ISSUE THREAD

**Issue by felaray** [AutoMapper/AutoMapper.Collection.EFCore#51]
My code is working in code first. but not working in db first.

**step:** 
1. Create table (name:user/todo) in SSMS
2. Create models by [EF core power tool ](https://github.com/ErikEJ/EFCorePowerTools)

**code:**
`var data = await _context.User.Persist(_mapper).InsertOrUpdateAsync(user); //pass`     
`await _context.SaveChangesAsync(); //throw ex`     

**ex:**
ex.Message	"The property 'User.Id' is part of a key and so cannot be modified or marked as modified. To change the principal of an existing entity with an identifying foreign key, first delete the dependent and invoke 'SaveChanges', and then associate the dependent with the new principal."	string

I tried for two days, any ideas? thanks

**Comment by TylerCarlson1** [comment]
If you get change set of the context before saving you can see which user is trying to update.  Also you can log the EF events and see what it's doing before save happens and see error occurring.

My best guess for actual problem is similar to that in EF6 which is discussed here https://github.com/AutoMapper/AutoMapper.Collection/issues/4
Also the stack overflow question explains how the problem happens.  At least in EF6 which should be similar https://stackoverflow.com/questions/11033348/is-it-possible-to-remove-child-from-collection-and-resolve-issues-on-savechanges

**Comment by felaray** [comment]
thx, I'll check my log.
